[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/transact/"
  to = "https://staging.dqfz18bztj8p7.amplifyapp.com/intent/pay/checkStatus"
  status = 301
  force = true
  
[[redirects]]
  from = "/checkStatus/payment-method-manifest.json"
  to = "https://staging.dqfz18bztj8p7.amplifyapp.com/intent/pay/checkStatus/payment-method-manifest.json"
  status = 301
  force = true

[[redirects]]
  from = "/checkStatus/payment-apay.json"
  to = "https://staging.dqfz18bztj8p7.amplifyapp.com/intent/pay/checkStatus/payment-apay.json"
  status = 301
  force = true
