[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[[redirects]]
  from = "/"
  to = "https://amazonpay.integ.amazon.com/intent/pay/checkStatus"
  status = 301
  force = true 
  
[[redirects]]
  from = "/intent/pay/checkStatus"
  to = "https://amazonpay.integ.amazon.com/intent/pay/checkStatus"
  status = 301
  force = true  
  
[[redirects]]
  from = "/intent/pay/checkStatus/"
  to = "https://amazonpay.integ.amazon.com/intent/pay/checkStatus"
  status = 301
  force = true
  
[[redirects]]
  from = "/intent/pay/checkStatus/payment-method-manifest.json"
  to = "https://amazonpay.integ.amazon.com/intent/pay/checkStatus"
  status = 301
  force = true

[[redirects]]
  from = "/intent/pay/checkStatus/payment-apay.json"
  to = "https://amazonpay.integ.amazon.com/intent/pay/checkStatus"
  status = 301
  force = true
