[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "https://staging.dqfz18bztj8p7.amplifyapp.com/intent/pay/checkStatusInfo/"
  status = 200
  force = true
